<Project Sdk="Dalamud.NET.Sdk/14.0.2">
  <PropertyGroup>
    <AssemblyName>SilverDasher.Core</AssemblyName>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <RootNamespace>SilverDasher</RootNamespace>
    <Use_DalamudPackager>false</Use_DalamudPackager>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MQTTnet" Version="*"/>
    <PackageReference Include="ImGui.NET" Version="*"/>
    <Reference Include="FFXIV_ACT_Plugin.Common">
      <HintPath>../../external_dependencies/SDK/FFXIV_ACT_Plugin.Common.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Content Include="SilverDasher.Weaver.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <ProjectReference Include="../../machina/Machina.FFXIV/Machina.FFXIV.csproj"/>
    <ProjectReference Include="../../NotACT/NotACT.csproj"/>
  </ItemGroup>
  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == ''">
    <DalamudLibPath>$(appdata)/XIVLauncherCN/addon/Hooks/dev</DalamudLibPath>
    <AssemblySearchPaths>$(AssemblySearchPaths);$(DalamudLibPath)</AssemblySearchPaths>
  </PropertyGroup>
  <PropertyGroup Condition="'$(GITHUB_ACTIONS)' == 'true'">
    <DalamudLibPath>$(appdata)/XIVLauncher/addon/Hooks/dev</DalamudLibPath>
    <AssemblySearchPaths>$(AssemblySearchPaths);$(DalamudLibPath)</AssemblySearchPaths>
  </PropertyGroup>
</Project>